name = "ziggy"
grammar = "ziggy"
path_suffixes = ["ziggy", "zgy"]
line_comments = ["// "]

brackets = [
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "{", end = "}", close = true, newline = false},
    { start = "[", end = "]", close = true, newline = false},
]
